config/routes.rb
Kupon::Application.routes.draw do
  resources :deals

  scope "(:locale)", :locale => /en|ru/ do
    devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks"}
    devise_scope :user do
      get "users"  => "devise/registrations#new"
    end
    authenticated do
      root :to => "dashboard#index"
    end

    unauthenticated do
      root :to => "dashboard#index"
    end
    
    put 'upload' => 'deals#upload'
    delete 'remove_upload/:id' => 'deals#remove_upload', :as=>:remove_upload
  end#scope locale

end

app/models/address.rb
class Address < ActiveRecord::Base
  attr_accessible :address, :city, :country, :deal_id, :integer, :phone, :province, :site, :zip
end

app/models/condition.rb
class Condition < ActiveRecord::Base
  attr_accessible :deal_id, :description, :type
  belongs_to :deal
  set_inheritance_column :condition_type
end

app/models/deal.rb
class Deal < ActiveRecord::Base
  attr_accessible :title, :description, :discount, :end_at, :start_at, :files_ids, :conditions_attributes
  attr_accessor :files_ids
  
  has_many :conditions
  has_many :prices
  has_many :addresses
  has_many :tikets
  has_many :images

  accepts_nested_attributes_for :conditions, :allow_destroy => true

  after_save :append_attachments
  
  validates_presence_of :description, :discount, :end_at, :start_at, :title
  validates :discount, :numericality => true
  validate :dates
  

  
  def dates
    self.errors.add(:start_at, :less_than_or_equal_to, :count=>Deal.human_attribute_name("end_at")) if self.start_at > self.end_at
  end
  
  protected
  def append_attachments
    unless files_ids.blank?
      files_ids.each do |attach|
        attachment = Image.find(attach)
        attachment.update_attributes({:deal_id => id}) if attachment
      end
    end
  end
  
end

app/models/image.rb
class Image < ActiveRecord::Base
  attr_accessible :attachment, :deal_id
  
  before_destroy :remember_id
  after_destroy :remove_id_directory

  mount_uploader :attachment, AttachmentUploader
  
  
  def thumb_url
    if self.attachment.is_pic? self.attachment.file
      self.attachment.thumb.url
    elsif self.attachment.is_pdf? self.attachment.file
      self.attachment.pdf_thumb.url
    elsif self.attachment.path.split('.').last.downcase == 'doc'
      '/assets/file_icon_doc.gif'
    else
      '/assets/icon_file.gif'
    end
  end
  
  def big_thumb_url
    if self.attachment.is_pic? self.attachment.file
      self.attachment.big_thumb.url
    elsif self.attachment.is_pdf? self.attachment.file
      self.attachment.big_pdf_thumb.url
    elsif self.attachment.path.split('.').last.downcase == 'doc'
      '/assets/file_icon_doc.gif'
    else
      '/assets/icon_file.gif'
    end
  end
  
  protected
  def remember_id
    @id = id
  end

  def remove_id_directory
    FileUtils.remove_dir("#{Rails.root}/public/uploads/#{Crypto.encrypt(@id.to_s)}", :force => true)
  end
end

app/models/price.rb
class Price < ActiveRecord::Base
  attr_accessible :amount, :condition, :deal_id
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  attr_accessible :code, :deal_id, :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :omniauthable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name
  
  validates_presence_of :first_name, :last_name
  
  def name
    "#{first_name} #{last_name}"
  end
  
  def self.find_for_open_id(access_token, signed_in_resource=nil)
    data = access_token.info
    if user = User.where(:email => data["email"]).first
      user
    else
      User.create!(:email => data["email"], :first_name=>data["first_name"], :last_name=>data["last_name"], :password => Devise.friendly_token[0,20])
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :set_locale
  before_filter :authenticate_user!
  
  def set_locale
    I18n.locale = "ru"#params[:locale]
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index

  end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  before_filter :find_deal, :only=>[:show, :edit, :update, :destroy]
  
  respond_to :html, :js
  
  def index
    @deals = Deal.all
    respond_with(@deals)
  end

  def show
    respond_with(@deal)
  end

  def new
    @deal = Deal.new
    respond_with(@deal)
  end

  def edit
  end

  def create
    @deal = Deal.new(params[:deal])

    respond_to do |format|
      if @deal.save
        format.html { redirect_to @deal, notice: 'Deal was successfully created.' }
        format.json { render json: @deal, status: :created, location: @deal }
      else
        format.html { render action: "new" }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @deal.update_attributes(params[:deal])
        format.html { redirect_to @deal, notice: 'Deal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @deal.destroy
    respond_to do |format|
      format.html { redirect_to deals_url }
      format.json { head :no_content }
    end
  end
  
  def upload
    attachment = Image.new
    attachment.save
    attachment.attachment = params["files"][0]
    attachment.save
    viewHelper = Object.new.extend(ActionView::Helpers::NumberHelper)
    render :json => ['name' => '<a href="' + attachment.attachment.to_s + '">' + params["files"][0].original_filename + '</a>', 'size' => viewHelper.number_to_human_size(File.size(params["files"][0].tempfile)), 'id' => attachment.id, 'thumb' => attachment.thumb_url, 'big_thumb' => attachment.big_thumb_url]
  end
  
  def remove_upload
    if params[:id] && Image.find(params[:id])
      Image.find(params[:id]).destroy
    end
    @remove_id = params[:id]
  end
  
  protected
  def find_deal
    @deal = Deal.find(params[:id])
  end
  
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google
    @user = User.find_for_open_id(request.env["omniauth.auth"], current_user)
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
  
  def vkontakte
    @user = User.find_for_open_id(request.env["omniauth.auth"], current_user)
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Vkontakte"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.vkontakte_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
  
  def facebook
    @user = User.find_for_open_id(request.env["omniauth.auth"], current_user)
    if @user.persisted?
      flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Facebook"
      sign_in_and_redirect @user, :event => :authentication
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def e(text)
    "'#{escape_javascript(text)}'".html_safe
  end

  def hidden;    { :style => "display:none;"       }; end
  def exposed;   { :style => "display:block;"      }; end
  def invisible; { :style => "visibility:hidden;"  }; end
  def visible;   { :style => "visibility:visible;" }; end
  def hidden_if(condiion); condiion ? hidden : {}; end

  def form_errors(resource)
    render(:partial => 'shared/errors', :locals => {:resource => resource }).html_safe
  end
  
  def datetime2str(t)
    return '' if t.nil?
    t = Time.parse(t.to_s) unless t.is_a?(DateTime)
    t.strftime("%Y-%m-%d %H:%M:%S")
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/views/dashboard/index.html.haml
Hello

app/views/deals/_carousel.html.haml
- images = @deal.images
- if images.any?
  - carousel_id = "carousel_#{@deal.id}"
  :css
    .carousel.slide{width:480px;}
    
  .carousel.slide.box{:id=>carousel_id}
    %ol.carousel-indicators
      - images.each_with_index do |image, ind|
        %li{:data=>{"slide-to"=>ind, :target=>"##{carousel_id}"}}
    .carousel-inner
      - images.each do |image|
        .item
          =image_tag image.attachment.url(:carousel_thumb)
          .carousel-caption
            %h4 hello
            %p this is the text that need to be pushed to description
    %a.left.carousel-control{:href=>"##{carousel_id}", "data-slide"=>"prev"}‹
    %a.right.carousel-control{:href=>"##{carousel_id}", "data-slide"=>"next"}›
  :javascript
    $('.carousel').carousel('cycle');

app/views/deals/_conditions_fields.html.haml
.control-group
    .controls= condition.text_area :description, :size => '10x5'

.control-group
    .controls
        = condition.text_field :type

.control-group
    .controls
        = condition.link_to_remove :class => "btn btn-warning", :id => "appendedInputButton" do
            %i.icon-remove

app/views/deals/_deal_attachments_fields.html.haml
- @deal.images.each do |image|
  - unless image.blank?
    - id = image.id
    .file_line{:id=>"file_row_#{id}"}
      .thumb
        %a.preview{:href=>image.big_thumb_url}
          =image_tag image.thumb_url
      .desc
        =link_to image.attachment.to_s.split('/').last, image.attachment_url
        ="(#{number_to_human_size(File.size("public/"+image.attachment.to_s))})"
        %input{:type=>"hidden", :name=>"deal[files_ids][]", :value=>id}
        %a{:href=>"/remove_upload/#{id}", :id=>"remove_file_#{id}", "data-remote"=>true, "data-method"=>"delete"}
          %i.icon-trash
  

app/views/deals/_deals.html.haml
.row
  - @deals.each do |deal|
    .span3.box
      .box-header
        =deal.title
      .box-content
        = deal.description.html_safe
      .box-footer
        .pull-right
          = link_to 'Show', deal, :class=>"btn btn-info"
          = link_to 'Edit', edit_deal_path(deal), :class=>"btn btn-success"
          = link_to 'Destroy', deal, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class=>"btn btn-danger"
    

app/views/deals/_form.html.haml
= javascript_include_tag "jquery.ui.widget.js"
= javascript_include_tag "jquery.fileupload.js"
= javascript_include_tag "jquery.iframe-transport.js"
= javascript_include_tag "file_upload.js"
= javascript_include_tag "modernizr.js"
= stylesheet_link_tag "file_upload.css"

:css
  form.form-horizontal textarea.wysihtml5{height:400px; width:100%;}

= nested_form_for @deal, :html=>{:class=>"form-horizontal"} do |f|
  = form_errors(@deal)
  .row
    .span8

      %ul{ :class=>"nav nav-tabs", :id => "dealTab" }
        %li.active
          %a{:href => "#general"} General
        %li
          %a{:href => "#images"} Images
        %li
          %a{:href => "#description"} Description
        %li
          %a{:href => "#conditions"} Conditions

      .tab-content
        #general.tab-pane.active
          .control-group
            = f.label :title, :class=>"control-label"
            .controls= f.text_field :title
          .control-group
            = f.label :discount, :class=>"control-label"
            .controls.input-append{:style=>"margin-left:20px;"}
              = f.number_field :discount
              %span.add-on %
          .control-group
            = f.label :start_at, :class=>"control-label"
            .controls.input-append.date#date_from{:style=>"margin-left:20px;"}
              - start_at = f.object.start_at.blank? ? Time.now : f.object.start_at
              = f.text_field :start_at, :data=>{:format=>"yyyy-MM-dd hh:mm:ss"}, :value => datetime2str(start_at)
              %span.add-on
                %i.icon-calendar{"data-time-icon"=>"icon-time", "data-date-icon"=>"icon-calendar"}
          .control-group
            - end_at = f.object.end_at.blank? ? Time.now : f.object.end_at
            = f.label :end_at, :class=>"control-label"
            .controls.input-append.date#date_to{:style=>"margin-left:20px;"}
              = f.text_field :end_at, :data=>{:format=>"yyyy-MM-dd hh:mm:ss"}, :value => datetime2str(end_at)
              %span.add-on
                %i.icon-calendar{"data-time-icon"=>"icon-time", "data-date-icon"=>"icon-calendar"}

        #images.tab-pane
          .control-group
            =f.label :files, :class=>"control-label"
            .controls
              #filesArea
              #dropZone
                -unless @deal.images.blank?
                  =render "deal_attachments_fields"
              %span.btn.fileinput-button
                %span= 'Add file...'
                %input#inputFile{:type => 'file'}

        #description.tab-pane
          = f.text_area :description, :class=>:wysihtml5, :placeholder=>"Enter text"

        #conditions.tab-pane
          = f.fields_for :conditions do |builder|
            = render "conditions_fields", :condition => builder

          .control-group
            = f.link_to_add t(:add_condition), :conditions

  .form-actions
    %button.btn.btn-large{:type=>"submit"}=t(:save)
    =link_to t(:cancel), :back, :class=>"btn btn-large"


=render "javascript"

app/views/deals/_javascript.html.haml
:javascript
  $("#date_from").datetimepicker({language:"#{I18n.locale}"});
  $("#date_to").datetimepicker({language:"#{I18n.locale}"});
  $('.wysihtml5').wysihtml5();
  $('#dealTab a').click(function (e) {
      e.preventDefault();
      $(this).tab('show');
  })

app/views/deals/_process_attachments_fields.html.haml
- @deal.images.each do |image|
  - unless image.blank?
    - id = image.id
    .file_line{:id=>"file_row_#{id}"}
      .thumb
        %a.preview{:href=>image.big_thumb_url}
          =image_tag image.thumb_url
      .desc
        =link_to image.attachment.to_s.split('/').last, image.attachment_url
        ="(#{number_to_human_size(File.size("public/"+image.attachment.to_s))})"
        %input{:type=>"hidden", :name=>"deal[files_ids][]", :value=>id}
        %a{:href=>"/remove_upload/#{id}", :id=>"remove_file_#{id}", "data-remote"=>true, "data-method"=>"delete"}
          %i.icon-trash
  

app/views/deals/edit.html.haml
%h1 Editing deal

= render 'form'

= link_to 'Show', @deal
\|
= link_to 'Back', deals_path

app/views/deals/index.html.haml
%h1 Listing deals
=render "deals"
= link_to 'New Deal', new_deal_path

app/views/deals/new.html.haml
%h1 New deal

= render 'form'

= link_to 'Back', deals_path

app/views/deals/remove_upload.js.erb
$("#file_row_" + <%= @remove_id %>).remove();

app/views/deals/show.html.haml
.row
  .span8
    %p#notice= notice
    
    %p
      %b Title:
      = @deal.title
    %p
      %b Description:
      = render "carousel"
      = @deal.description.html_safe
    %p
      %b Start at:
      = @deal.start_at
    %p
      %b End at:
      = @deal.end_at
    %p
      %b Discount:
      = @deal.discount
    
    = link_to 'Edit', edit_deal_path(@deal)
    \|
    = link_to 'Back', deals_path

app/views/layouts/_modal.html.haml
.modal.hide.fade
  .modal-header
    %button.close{:type=>"button", :data=>{:dismiss=>"modal"}, :aria=>{:hidden=>"true"}} &times;
    <h3>Header</h3>
  .modal-body
  .modal-footer

app/views/layouts/_navbar.html.haml
.navbar.navbar-inverse.navbar-fixed-top
  .navbar-inner
    .container-fluid
      %button.btn.btn-navbar.collapsed{:data=>{:target=>".nav-collapse", :toggle=>"collapse"}, :type=>"button"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.brand{:href=>"#"}Kupon
      .nav-collapse.collapse
        %p.navbar-text.pull-right
          -if user_signed_in?
            %span="Hello #{current_user.name}! "
            =link_to t(:sign_out), destroy_user_session_path
          -else
            =link_to t(:sign_in), new_user_session_path
            \/
            =link_to t(:sign_up), new_user_registration_path
        %ul.nav
          %li
            %a{:href=>"#"} Item 1
          %li
            %a{:href=>"#"} Item 2
          %li
            %a{:href=>"#"} Item 3
        

app/views/layouts/_sidebar.html.haml
.well.sidebar-nav
  %ul.nav.nav-list
    %li.nav-header
      title
    %li.active
      %a{:href=>"#"} Item 1
    %li
      %a{:href=>"#"} Item 2
    %li
      %a{:href=>"#"} Item 3

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Kupon
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    %meta{"http-equiv"=>"Content-Type", "content"=>"text/html; charset=utf-8"}
  %body
    = render 'layouts/navbar'
    .container-fluid
      =yield
    =render "layouts/modal"
    

app/views/shared/_empty.html.haml
.empty_list= message ||= t(:empty_list)

app/views/shared/_errors.html.haml
-if resource.errors.any?
  %div{:class=>"alert alert-error"}
    %a{:class=>"close", "data-dismiss"=>"alert"}
    %h2= t(:form_error, :number =>  t(:form_error_number, :count => resource.errors.count))
    %ul
      - resource.errors.full_messages.each do |msg|
        %li= msg